"""Company branding shared by every report."""
from __future__ import annotations

import io
from pathlib import Path

from openpyxl.drawing.image import Image as XlImage
from openpyxl.styles import Alignment, Font

COMPANY = "DataVers.AI"
TAGLINE = "Engineering Intelligence"
PRODUCT = "Drawing Intelligence"
VERSION = "0.1.0"
COPYRIGHT = f"© 2026 {COMPANY} · {TAGLINE} · All rights reserved"
CREDIT = f"Generated by {PRODUCT} v{VERSION} · {COMPANY}"
LOGO_PATH = Path(__file__).with_name("logo.png")  # white + cyan wordmark on brand navy, 640×160

CREDIT_FONT = Font(name="Arial", size=8, italic=True, color="666666")


def logo_bytes() -> bytes:
    return LOGO_PATH.read_bytes()


def place_logo(ws, anchor: str, height_px: int = 40) -> None:
    """Navy logo chip at the given cell; the sheet's title row is made tall enough to hold it."""
    img = XlImage(io.BytesIO(logo_bytes()))
    ratio = img.width / img.height
    img.height, img.width = height_px, int(height_px * ratio)
    ws.add_image(img, anchor)


def credit_row(ws, row: int, cols: int) -> None:
    ws.merge_cells(start_row=row, start_column=1, end_row=row, end_column=cols)
    c = ws.cell(row=row, column=1, value=f"{CREDIT}   {COPYRIGHT}")
    c.font = CREDIT_FONT
    c.alignment = Alignment(horizontal="right", vertical="center")
    ws.row_dimensions[row].height = 14
